//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ_To_SQL.Data_Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Details
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public Nullable<int> Sallary { get; set; }
        public string Gender { get; set; }
    }
}
